[package]
name = "token_linker"
version = "0.0.1"

[addresses]
deployer = "0x8ac1b8ff9583ac8e661c7f0ee462698c57bb7fc454f587e3fa25a57f9406acc0"
token_linker = "0x1641cde81bb0ffd52cce178f6ab4f1fc86fe451de189ffc71298aaf2e74a7a15"

[dependencies]
AxelarFramework = {  git = "https://github.com/axelarnetwork/axelar-cgp-aptos.git", subdir ="aptos/modules/axelar", rev = "main" }
