name: Run tests gmp examples

on:
  push:
    branches:    
      - feat/run-tests 

jobs:
  release-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [amd64]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prerequisites
        run: |
          wget --no-check-certificate  https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v1.0.1/aptos-cli-1.0.1-Ubuntu-22.04-x86_64.zip
          unzip aptos-cli-1.0.1-Ubuntu-22.04-x86_64.zip
          chmod +x aptos
          cp aptos /usr/local/bin

      - name: Build and test
        run: |
          npm audit fix
          npm install
          npm run build 
          npm run test




