name: Run tests gmp examples

on:
  push:
    branches:    
      - feat/run-tests 

jobs:
  release-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [amd64]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install npm@latest -g
          npm install --save-dev hardhat
          yarn build

      - name: Test
        run: |
          yarn test

