name: Run tests gmp examples

on:
  push:
    branches:    
      - feat/run-tests 

jobs:
  release-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [amd64]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prerequisites
        run: |
          git clone https://github.com/aptos-labs/aptos-core.git
          cd scripts
          chmod +x dev_setup.sh
          ./dev_setup.sh

      - name: Build
        run: |
          npm install
          npm run build

      - name: Test
        run: |
          npm run test

